name: Generate and commit new Docker material for benchmarks

on:
  workflow_dispatch:
    inputs:
      commitMessage:
        description: 'Message for Dockerfile generation commit'
        required: true
        default: 'Creates new Docker material for individual benchmarks'
        type: 'string'
      branchName:
        description: 'Name of branch to be created'
        required: true
        default: 'dockerfile_generation'
        type: 'string'
      # prName:
      #   description: 'Name of the pull request to generate'
      #   required: true
      #   default: 'Creates new Docker material for individual benchmarks'
      #   type: 'string'
      # prBody:
      #   description: 'Body for the pull request to generate'
      #   required: true
      #   default: ''
      #   type: 'string'

jobs:
  gen-and-commit-docker:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Jinja
      run: |
        python3 -m pip install Jinja2

    - name: Generate new Docker material for benchmarks
      run: |
        python3 ./docker/create_docker_for_benchmarks.py
    
    - name: Commit new Docker material and create PR
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: ${{ inputs.commitMessage }}
        branch: ${{ inputs.branchName }}
        # title: ${{ inputs.prName }}
        # body: ${{ inputs.prBody }}